# default config
baseURL = "/"
languageCode = "en-us"
title = "Chilli and Lime - Asian flavours with an awesome twist"
summaryLength = "10"
paginate = 6

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"

# navigation
[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Recipes"
URL = "recipes"
weight = 3

# [[menu.main]]
# name = "Blog"
# URL = "blog"
# weight = 4

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5

# deult parameter
[params]
logo = "images/logo-small.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" ) DO NOT CHANGE THIS!!!
layout = "1"
# Meta data
description = "Asian food with an awesome twist."
# about author
author = "Mina"
author_image = "images/banner-img.png"
bio = "I'm a photographer, watercolor artist and calligrapher from Thailand. Welcome to my corner of the internet."
# Contact info
email = "mina@chilliandlime.net"
# Contact Form Action
contact_form_action = "#"
# Google Analytics
google_analytics_id = "UA-97831455-1"
# copyright
copyright = "Copyright &copy; 2020 [Chilli and Lime](/). Chilli and Lime is personal blog containing only original content."

# Preloader
[params.preloader]
enable = true

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/chilliandlimeblog"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/chilliandlimeblog/"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/chilliandlimeth"

[[params.social]]
icon = "ti-pinterest"
URL = "https://www.pinterest.com/chilliandlimeblog/"

[markup.goldmark.renderer]
unsafe= true
