# default config
baseURL = "/"
languageCode = "en-us"
title = "Chilli and Lime - Asian flavours with an awesome twist"
summaryLength = "10"
paginate = 6

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Recipes"
URL = "recipes"
weight = 3

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5

# deult parameter
[params]
logo = "images/logo-small.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "Asian food with an awesome twist."
# about author
author = "Mina"
author_image = "images/banner-img.png"
bio = "I'm a photographer, watercolor artist and calligrapher from Thailand. Welcome to my corner of the internet."
# Contact info
email = "mina@chilliandlime.net"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright &copy; 2020 [Chilli and Lime](/)"

# Preloader
[params.preloader]
enable = true

# search
[params.search]
enable = true

# Instagram feed
[params.instafeed]
enable = true
user_id = "863669960759354"
access_token = "ad6e06451d49a38137d6df13ae245c6c"

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/chilliandlimeblog"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/chilliandlimeth"

[[params.social]]
icon = "ti-linkedin"
URL = "https://instagram.com/chilliandlimeblog"

[[params.social]]
icon = "ti-pinterest"
URL = "https://www.pinterest.com/chilliandlimeblog/"
