# default config
baseURL = "/"
languageCode = "en-us"
title = "Chilli and Lime - Asian flavours with an awesome twist"
summaryLength = "10"
paginate = 6

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"

# navigation
[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Recipes"
URL = "recipes"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

[[menu.main]]
name = "Keto / Low Carb"
URL = "keto"
weight = 5
parent = "Recipes"

[[menu.main]]
name = "Vegan / Vegetarian"
URL = "vegetarian"
weight = 6
parent = "Recipes"

[[menu.main]]
name = "Asian Flavours"
URL = "asian"
weight = 7
parent = "Recipes"

[[menu.main]]
name = "Homesteading"
URL = "homesteading"
weight = 8
parent = "Recipes"

[[menu.main]]
name = "All"
URL = "recipes"
weight = 9
parent = "Recipes"

# deult parameter
[params]
logo = "images/logo-small.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" ) DO NOT CHANGE THIS!!!
layout = "1"
# Meta data
description = "Asian food with an awesome twist."
# about author
author = "Mina"
image = "https://s.gravatar.com/avatar/8f08d0d1922a14fcb3398b7ff9bb0a9f?s=200"
bio = "Hi, I'm Mina. I'm a photographer, recipe developer, watercolor artist and calligrapher from Thailand. I love food and cooking new recipes, so I created this website to share my recipes and food photography with the world. Welcome, you will find all kinds of different cooking here - mostly Asian food, but there are ketogenic as well as vegan and vegetarian recipes, and even a few basic homesteading type ideas. Click on your favourite topic above, or click below to see the most recent recipes. I hope you like what you find!"
# Contact info
email = "mina@chilliandlime.net"
privacy-policy = '/privacy-policy'
# Contact Form Action
contact_form_action = "#"
# Google Analytics
googleAnalytics = "UA-97831455-1"
# copyright
copyright = "Copyright &copy; 2020 [Chilli and Lime](/). Chilli and Lime is personal blog containing only original content."
addThis = "ra-5e7b794a35f33f1b"

# Preloader
[params.preloader]
enable = true

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/chilliandlimeblog"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/chilliandlimeblog/"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/chilliandlimeth"

[[params.social]]
icon = "ti-pinterest"
URL = "https://www.pinterest.com/chilliandlimeblog/"

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  category = "categories"
  tag = "tags"
