name = "Chilli and Lime"
license = "MIT"
licenselink = "https://github.com/andyst81/chilli-lime/blob/master/LICENSE"
description = "Hugo port of the Themefisher’s Parsa Template"
homepage = "https://chilliandlime.net"


[author]
  name = "Andy T"
  homepage = "https://bootlegninja.space/"
