name = "Chilli and Lime"
license = "MIT"
licenselink = "https://github.com/andyst81/chilli-lime/blob/master/LICENSE"
homepage = "https://chilliandlime.net"

[author]
  name = "Andy T"
  homepage = "https://bootlegninja.space/"
